# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- none

parameters:
  - name: testvar1
    displayName: test prima variabila parametru
    type: string
  - name: test
    displayName: Run Tests?
    type: boolean
    default: false

pool: neso
  #vmImage: ubuntu-latest

  ### un mic comment
strategy:
  matrix:
    Python39:
      python.version: '3.9'  

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#   displayName: 'Use Python $(python.version)'

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'

- script: |
    curl -4 ip.me
  displayName: 'ip-ul agentului'

- ${{ if eq(parameters.test, true) }}:
  - script: echo "Running all the tests"